import {useState} from 'react'
import {fitsJokeAge,getJokeById,jokes} from '../data/jokes'

const planets=[['math','🪐','数学星球','和数字一起探索规律','math'],['english','🦊','英文乐园','听一听，大胆开口说','english'],['reading','🏰','阅读城堡','从短文里发现线索','reading'],['brain','🧠','脑力实验室','练习记忆、观察和推理','brain'],['life','🏡','生活小镇','学会照顾自己和别人','life'],['story','🌙','晓芳妈妈故事屋','每天一个温柔故事','story'],['jokes','🐧','冷笑话冰箱','每天笑一下，小脑袋轻松一下','joke'],['growth','🌱','我的成长','看看自己点亮的小脚印','growth']]
const recommendations={5:'数学 + 情绪表达',6:'英文 + 脑力记忆',7:'数学 + 阅读',8:'阅读 + 生活能力',9:'数学推理 + 英文短文',10:'独立思考 + 时间管理'}

export default function Home({state,navigate,onViewJoke}){const [showJoke,setShowJoke]=useState(false);const today=new Date().toLocaleDateString('en-CA');const ageJokes=jokes.filter(joke=>fitsJokeAge(joke,state.selectedAge));const savedDaily=getJokeById(state.dailyJokeId);const daily=state.dailyJokeDate===today&&savedDaily&&fitsJokeAge(savedDaily,state.selectedAge)?savedDaily:ageJokes[dayNumber(today)%ageJokes.length];function reveal(){setShowJoke(true);onViewJoke(daily,{daily:true})}return <><section className="home-hero"><div className="hero-sky" aria-hidden="true"><span>⭐</span><span>☁️</span><span>🌙</span></div><div className="mascot">🦊<span>🚀</span></div><p className="eyebrow">嗨，Jason！今天也一起长大</p><h1>成长小宇宙</h1><p className="hero-copy">每天一点点，慢慢变聪明，慢慢变勇敢。</p><button className="hero-cta" onClick={()=>navigate('today')}>🚀 开始今天的任务</button><div className="home-stats five"><div><b>⭐ {state.totalStars}</b><span>我的星星</span></div><div><b>🔥 {state.dailyStreak}</b><span>连续天数</span></div><div><b>✅ {state.completedSessions}</b><span>完成任务</span></div><div><b>📖 {state.heardStoriesTotal}</b><span>听过故事</span></div><div><b>😄 {state.viewedJokes.length}</b><span>看过笑话</span></div></div></section><section className="home-content"><article className="recommend-card"><div><span className="mini-label">今日推荐 · {state.selectedAge} 岁</span><h2>今天适合练习：{recommendations[state.selectedAge]}</h2><p>完成 {state.sessionLength} 分钟小任务，再听一个温柔故事吧。</p></div><span className="recommend-planet" aria-hidden="true">🌈</span></article><article className="home-joke-card"><span>🐧 今日冷笑话</span><h2>{daily.setup}</h2>{showJoke&&<p>😄 {daily.punchline}</p>}<div><button onClick={reveal}>看答案</button><button onClick={()=>navigate('jokes')}>打开冷笑话冰箱</button></div><small>已收藏 {state.favoriteJokes.length} 个笑话</small></article><div className="section-heading"><div><p className="eyebrow">选择一个方向</p><h2>探索星球地图</h2></div><button onClick={()=>navigate('map')}>查看全部 →</button></div><div className="planet-grid">{planets.map(([id,icon,title,copy,tone])=><article className={`planet-card ${tone}`} key={id}><span className="planet-art" aria-hidden="true">{icon}</span><div><h3>{title}</h3><p>{copy}</p><button onClick={()=>navigate(id)}>进入探索</button></div></article>)}</div><div className="home-quick-links"><button onClick={()=>navigate('today')}>✅ 今日任务</button><button onClick={()=>navigate('settings')}>👩 家长入口</button></div><article className="story-feature"><div className="story-moon" aria-hidden="true">🌙</div><div><span className="mini-label">今日故事 · 温柔陪伴</span><h2>晓芳妈妈故事屋</h2><p>每天一个温柔故事，妈妈陪你慢慢长大。</p><button onClick={()=>navigate('story')}>进入故事屋</button></div><div className="clouds" aria-hidden="true">☁️ ✨ ☁️</div></article></section></>}

function dayNumber(date){return [...date].reduce((sum,char)=>sum+char.charCodeAt(0),0)}
