import {useMemo,useState} from 'react'
import {getCategoryLabel,getStoryById,stories,storyCategories} from '../data/stories'

export default function StoryHouse({state,onRead,onFavorite}){
  const [category,setCategory]=useState('all')
  const [query,setQuery]=useState('')
  const [selectedId,setSelectedId]=useState(null)
  const [companion,setCompanion]=useState(false)
  const [night,setNight]=useState(false)
  const selected=getStoryById(selectedId)
  const filtered=useMemo(()=>{const pool=category==='all'?stories:stories.filter(story=>story.category===category);const word=query.trim().toLowerCase();return word?pool.filter(story=>`${story.title}${story.summary}${story.theme}`.toLowerCase().includes(word)):pool},[category,query])
  const favoriteCategory=Object.entries(state.storyCategoryCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]

  if(selected)return <section className={`story-reader ${companion?'companion':''} ${night?'night':''}`}><div className="reader-toolbar"><button onClick={()=>setSelectedId(null)}>← 返回故事屋</button><div><button onClick={()=>onFavorite(selected.id)} aria-label={state.favoriteStoryIds.includes(selected.id)?'取消收藏故事':'收藏故事'}>{state.favoriteStoryIds.includes(selected.id)?'♥ 已收藏':'♡ 收藏'}</button><button onClick={()=>setCompanion(!companion)}>{companion?'普通阅读':'妈妈陪读'}</button><button onClick={()=>setNight(!night)}>{night?'☀️ 日间':'🌙 夜晚'}</button></div></div><header><span className="story-category">{getCategoryLabel(selected.category)}</span><h1>{selected.title}</h1><p>{selected.ageRange} 岁 · {selected.readingTime} · {selected.theme}</p></header><article className="story-text">{selected.text.split('。').filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}。</p>)}</article><StorySection icon="💎" title="词语小宝箱"><div className="word-chips">{selected.vocabulary.map(word=><span key={word}>{word}</span>)}</div></StorySection><StorySection icon="🎙️" title="妈妈朗读提示"><ul>{selected.readingTips.map(tip=><li key={tip}>{tip}</li>)}</ul></StorySection><StorySection icon="💭" title="想一想"><ol>{selected.questions.map(question=><li key={question}>{question}</li>)}</ol></StorySection><StorySection icon="🤗" title="亲子小问题"><ul>{selected.parentPrompts.map(question=><li key={question}>{question}</li>)}</ul></StorySection><div className="gentle-card"><span>✨ 今天学到的一句话</span><strong>{selected.gentleSentence}</strong></div><div className="little-task"><span>🌱 小小任务</span><p>{selected.littleTask}</p></div><article className="mom-message"><span aria-hidden="true">💗 🌙 ✨</span><h2>妈妈想对你说</h2><p>{selected.momMessage}</p></article><button className="complete-story" onClick={()=>onRead(selected)}>✅ 已读完成，点亮故事星星</button></section>

  const recent=getStoryById(state.recentStoryIds[0])
  return <section className="story-house"><header className="story-house-hero"><div aria-hidden="true">🌙</div><p className="eyebrow">妈妈陪伴 · 温柔成长</p><h1>晓芳妈妈故事屋</h1><p>这里有妈妈可以读给宝宝听的故事，也有宝宝可以慢慢学会的勇气、温柔和生活智慧。</p><button onClick={()=>setSelectedId(stories[new Date().getDate()%stories.length].id)}>阅读今日推荐故事</button></header><div className="story-dashboard"><div><b>{state.readStoryIds.length}</b><span>已读故事</span></div><div><b>{state.favoriteStoryIds.length}</b><span>收藏故事</span></div><div><b>{favoriteCategory?getCategoryLabel(favoriteCategory):'等你发现'}</b><span>最喜欢分类</span></div></div>{recent&&<button className="recent-story" onClick={()=>setSelectedId(recent.id)}>📖 最近读过：《{recent.title}》 继续阅读 →</button>}<label className="story-search">🔎<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索故事标题、主题……" aria-label="搜索故事"/></label><div className="category-tabs" role="tablist"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>全部故事</button>{storyCategories.map(item=><button key={item.id} className={category===item.id?'active':''} onClick={()=>setCategory(item.id)}>{item.icon} {item.label}</button>)}</div><div className="story-grid">{filtered.map(story=><article key={story.id} className="story-card"><div className="story-card-top"><span>{storyCategories.find(item=>item.id===story.category)?.icon}</span><button className={state.favoriteStoryIds.includes(story.id)?'saved':''} onClick={()=>onFavorite(story.id)} aria-label={state.favoriteStoryIds.includes(story.id)?'取消收藏':'收藏故事'}>{state.favoriteStoryIds.includes(story.id)?'♥':'♡'}</button></div><span className="story-category">{getCategoryLabel(story.category)}</span><h2>{story.title}</h2><p>{story.summary}</p><div className="story-meta"><span>{story.ageRange} 岁</span><span>{story.readingTime}</span><span>{story.theme}</span></div><button className="read-button" onClick={()=>setSelectedId(story.id)}>开始阅读</button></article>)}</div>{filtered.length===0&&<p className="empty-state">没有找到这个故事，换一个词试试吧。</p>}</section>
}

function StorySection({icon,title,children}){return <section className="story-learning"><h2>{icon} {title}</h2>{children}</section>}
