export const defaults={selectedAge:'7',difficulty:'普通',sessionLength:'10',trainingFocus:'综合训练',totalStars:0,todayStars:0,todayDate:'',dailyStreak:0,completedSessions:0,lastCompletedDate:'',badges:[],readStoryIds:[],favoriteStoryIds:[],recentStoryIds:[],storyCategoryCounts:{},readStories:[],favoriteStories:[],recentStories:[],storyCategoryStats:{},heardStoriesTotal:0,lastStoryDate:'',viewedJokes:[],favoriteJokes:[],recentJokes:[],jokeCategoryStats:{},dailyJokeDate:'',dailyJokeId:'',customJokes:[],answerHistory:[],skillRecords:[],parentPin:'1234',growthFootprints:[]}
function parse(raw,fallback){try{return JSON.parse(raw)}catch{return fallback}}
export function load(){const data={};for(const [k,v] of Object.entries(defaults)){const raw=localStorage.getItem(k);if(raw===null){data[k]=v;continue}data[k]=typeof v==='number'?Number(raw):typeof v==='object'?parse(raw,v):raw}data.readStoryIds=[...new Set([...data.readStoryIds,...data.readStories])];data.favoriteStoryIds=[...new Set([...data.favoriteStoryIds,...data.favoriteStories])];data.recentStoryIds=data.recentStoryIds.length?data.recentStoryIds:data.recentStories;data.storyCategoryCounts=Object.keys(data.storyCategoryCounts).length?data.storyCategoryCounts:data.storyCategoryStats;data.readStories=data.readStoryIds;data.favoriteStories=data.favoriteStoryIds;data.recentStories=data.recentStoryIds;data.storyCategoryStats=data.storyCategoryCounts;data.skillRecords=data.answerHistory.length?data.answerHistory:data.skillRecords;const today=new Date().toLocaleDateString('en-CA');if(data.todayDate!==today)data.todayStars=0;return data}
export function save(data){Object.entries(data).forEach(([k,v])=>localStorage.setItem(k,typeof v==='object'?JSON.stringify(v):String(v)))}
export function reset(){Object.keys(defaults).forEach(k=>localStorage.removeItem(k));return {...defaults}}

export function exportProgress(){return JSON.stringify(load(),null,2)}
export function importProgress(text){const parsed=JSON.parse(text);const safe={...defaults,...parsed};save(safe);return safe}

export function recordStory(state,story){const today=new Date().toLocaleDateString('en-CA');const isNew=!state.readStoryIds.includes(story.id);const readStoryIds=[...new Set([...state.readStoryIds,story.id])];const recentStoryIds=[story.id,...state.recentStoryIds.filter(id=>id!==story.id)].slice(0,5);const counts={...state.storyCategoryCounts,[story.category]:(state.storyCategoryCounts[story.category]||0)+(isNew?1:0)};return {...state,readStoryIds,readStories:readStoryIds,recentStoryIds,recentStories:recentStoryIds,storyCategoryCounts:counts,storyCategoryStats:counts,heardStoriesTotal:state.heardStoriesTotal+(isNew?1:0),lastStoryDate:today,growthFootprints:[...state.growthFootprints,{date:today,text:`读完了《${story.title}》`}].slice(-20)} }

export function toggleFavorite(state,id){const favoriteStoryIds=state.favoriteStoryIds.includes(id)?state.favoriteStoryIds.filter(item=>item!==id):[...state.favoriteStoryIds,id];return {...state,favoriteStoryIds,favoriteStories:favoriteStoryIds}}

export function recordAnswer(state,entry){const answerHistory=[...state.answerHistory,{...entry,at:new Date().toISOString()}].slice(-500);return {...state,answerHistory,skillRecords:answerHistory}}

export function recordJoke(state,joke,{daily=false}={}){const today=new Date().toLocaleDateString('en-CA');const isNew=!state.viewedJokes.includes(joke.id);const viewedJokes=[...new Set([...state.viewedJokes,joke.id])];const counts={...state.jokeCategoryStats,[joke.category]:(state.jokeCategoryStats[joke.category]||0)+(isNew?1:0)};const badges=[...state.badges];if(viewedJokes.length>=5&&!badges.includes('笑一笑徽章'))badges.push('笑一笑徽章');return {...state,viewedJokes,badges,recentJokes:[joke.id,...state.recentJokes.filter(id=>id!==joke.id)].slice(0,8),jokeCategoryStats:counts,...(daily?{dailyJokeDate:today,dailyJokeId:joke.id}:{})}}

export function toggleJokeFavorite(state,id){const favoriteJokes=state.favoriteJokes.includes(id)?state.favoriteJokes.filter(item=>item!==id):[...state.favoriteJokes,id];const badges=[...state.badges];if(favoriteJokes.length>=5&&!badges.includes('冷笑话收藏家'))badges.push('冷笑话收藏家');return {...state,favoriteJokes,badges}}

export function addCustomJoke(state,text){const joke={id:`custom-${Date.now()}`,text,createdAt:new Date().toISOString()};const customJokes=[joke,...state.customJokes].slice(0,50);const badges=[...state.badges];if(customJokes.length>=3&&!badges.includes('小小段子手'))badges.push('小小段子手');return {...state,customJokes,badges,growthFootprints:[...state.growthFootprints,{date:new Date().toLocaleDateString('en-CA'),text:'编出了一个自己的小笑话'}].slice(-20)}}
